[project]
name = "neuralmint-contracts"
description = "NeuralMint Stacks contracts"
authors = ["Serkan <serkan@swissdigital.ch>"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = "2.5"

[contracts.neuralmint-nft]
path = "contracts/neuralmint-nft.clar"
clarity_version = 2
epoch = "2.5"

[contracts.neuralmint-marketplace]
path = "contracts/neuralmint-marketplace.clar"
clarity_version = 2
epoch = "2.5"

[contracts.neuralmint-lazy-mint]
path = "contracts/neuralmint-lazy-mint.clar"
clarity_version = 2
epoch = "2.5"
